from shop import app
from shop import db
from shop.models import Item, User


#Checks if the run.py file has executed directly and not imported
if __name__ == '__main__':
        #Creates the database
        # with app.app_context():
        #         db.create_all()
        #          #Creates the items in database
        #         items = [Item(id=1, name='2099 Iron Man Suit', price=15000, description='Introducing the ultimate embodiment of technological innovation - the Iron Man suit! This awe-inspiring suit is the pinnacle of human engineering and a true testament to the possibilities of modern technology.Crafted from state-of-the-art materials and outfitted with cutting-edge components, the Iron Man suit boasts incredible strength, durability, and agility, allowing the wearer to perform superhuman feats with ease. With its sleek, streamlined design and stunning visual aesthetics, the Iron Man suit is sure to turn heads and make a bold statement wherever it goes. But its not just about the looks - the Iron Man suit is packed with an array of advanced features that make it the ultimate tool for any high-stakes mission. From its built-in weapons and advanced targeting systems to its self-contained life support and environmental control systems, this suit has everything you need to take on any challenge and emerge victorious. And with its customizable interface and intuitive controls, the Iron Man suit is easy to use and adapt to your specific needs. Whether you are a seasoned warrior or a beginner just starting out, the Iron Man suit is the perfect choice for anyone looking to push the limits of whats possible', environmental_impact=30),
        #                  Item(id=2, name='The First Lightsaber', price=10000, description='Introducing the one-of-a-kind, revolutionary weapon that has changed the course of history - the very first lightsaber ever created! Crafted with the utmost care and precision, this elegant and sophisticated weapon is unlike anything the galaxy has ever seen before. It harnesses the power of a rare and mystical energy source, known as the Force, and uses it to produce a blade of pure, radiant light. Not only is the lightsaber an incredibly powerful weapon, but it is also a work of art. With its sleek design and intricate detailing, the first lightsaber is a true masterpiece, crafted with the finest materials available in the galaxy. But it iss not just about the aesthetics - the first lightsaber is a highly versatile tool, capable of cutting through almost anything with ease. Its unique technology allows for unparalleled precision and control, making it the perfect weapon for even the most challenging of combat situations. And with its legendary reputation and storied history, the first lightsaber is a true collectors item. This iconic weapon has played a pivotal role in the galaxys most historic events, making it a must-have for any serious collector or fan of galactic history.', environmental_impact=15),
        #                  Item(id=3, name='The Martian Spacesuit', price=3500, description='Introducing the most advanced spacesuit ever designed - the spacesuit from the blockbuster movie, The Martian! This suit is the ultimate in astronaut safety and protection, designed to withstand the harsh and unforgiving environment of space. It is equipped with an array of cutting-edge features that ensure the wearers survival, no matter the conditions. The spacesuit is made from the most advanced materials available, including Kevlar and Nomex, to provide maximum protection against extreme temperatures, radiation, and debris. Its modular design allows for quick and easy repair in case of damage. But the spacesuit is more than just a protective layer - it is also a technological marvel. The suits integrated life support system provides breathable air, and a waste management system that recycles waste and converts it into breathable air. The spacesuits helmet is equipped with a high-definition display that allows the wearer to view important information and navigate their surroundings. The suit is also fitted with a personal audio system, providing clear communication between astronauts and mission control. This suit has been tested in the most extreme environments, and its reliability and durability have been proven time and time again. It is the perfect choice for any astronaut looking to embark on an epic mission, or for any collector looking to own a piece of movie history.', environmental_impact=5),
        #                  Item(id=4, name='Batmans Batwing', price=20000, description='Introducing the ultimate crime-fighting machine - the Batwing! This state-of-the-art aircraft is the pinnacle of human engineering and a true testament to the possibilities of modern technology. With its sleek, streamlined design and cutting-edge technology, the Batwing is the perfect tool for any high-stakes mission. Its advanced weapons systems and stealth capabilities make it the ultimate weapon against crime. And with its customizable interface and intuitive controls, the Batwing is easy to use and adapt to your specific needs. Whether you are a seasoned crime-fighter or a beginner just starting out, the Batwing is the perfect choice for anyone looking to push the limits of whats possible.', environmental_impact=30)]
        #         #Adds the items to the database
        #         for item in items:
        #                 db.session.add(item)
        #                 db.session.commit()

        #         user = User(id=1, username='admin', email_address='admin.co.uk', password='admin')
        #         db.session.add(user)
        #         db.session.commit()
        #Runs the app
        app.run(debug=True)